var annotated_dup =
[
    [ "Circle", "class_circle.html", "class_circle" ],
    [ "CircleDetector", "class_circle_detector.html", "class_circle_detector" ],
    [ "Color", "class_color.html", null ],
    [ "ConvexPolygon", "class_convex_polygon.html", "class_convex_polygon" ],
    [ "DrawServerVisitor", "class_draw_server_visitor.html", "class_draw_server_visitor" ],
    [ "Error", "class_error.html", "class_error" ],
    [ "Group", "class_group.html", "class_group" ],
    [ "LoadWithText", "class_load_with_text.html", "class_load_with_text" ],
    [ "Matrix2_2", "class_matrix2__2.html", "class_matrix2__2" ],
    [ "Polygon", "class_polygon.html", "class_polygon" ],
    [ "PolygonDetector", "class_polygon_detector.html", "class_polygon_detector" ],
    [ "SaveInText", "class_save_in_text.html", "class_save_in_text" ],
    [ "Segment", "class_segment.html", "class_segment" ],
    [ "SegmentDetector", "class_segment_detector.html", "class_segment_detector" ],
    [ "ServerConnection", "class_server_connection.html", "class_server_connection" ],
    [ "Shape", "class_shape.html", "class_shape" ],
    [ "ShapeDetector", "class_shape_detector.html", "class_shape_detector" ],
    [ "ShapeDetectorCOR", "class_shape_detector_c_o_r.html", "class_shape_detector_c_o_r" ],
    [ "ShapeManagerVisitor", "class_shape_manager_visitor.html", "class_shape_manager_visitor" ],
    [ "ShapesManager", "class_shapes_manager.html", "class_shapes_manager" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "Vector2D", "class_vector2_d.html", "class_vector2_d" ]
];